### ISSUE TITLE
Add a repository field for npmjs.com

### ISSUE THREAD

**Issue by brettz9** [w8r/rollup-buble-mocha-boilerplate#1]
Hi there,

Your project looks nice but I almost didn't visit it as I normally check out the source and didn't see the usual link to it. If you add the `repository` field to `package.json`, it should show up.

Thanks!

**Comment by brettz9** [comment]
Also, it appears `module` is now preferred over `jsnext:main` per https://github.com/rollup/rollup/wiki/pkg.module

**Comment by brettz9** [comment]
And, out of curiosity, why does your eslintignore use airbnb over say the "standard" syntax?  https://github.com/standard/eslint-config-standard

**Comment by brettz9** [comment]
And a few other nits:

1. `rollup.config.js`:
`entry` is now input
`moduleName` is now output.name
`sourceMap` is now output.sourcemap
`dest` is now output.file
`format` is now output.format

2.
```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

And some of your devDependencies are now out of date. (Greenkeeper or at least npm-check-updates might help)

I'd also recommend adding `yarn.lock`.

(And I'm only nitpicking as I was so pleased to find such a needed combo!)

**Comment by brettz9** [comment]
And while I'm spamming you... Since you already anticipated a browser build, why not a Mocha index like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Testing library</title>

    <link rel="stylesheet" href="../node_modules/mocha/mocha.css" />
  </head>
  <body>
    <div id="mocha"></div>

    <script src="../node_modules/source-map-support/browser-source-map-support.js"></script>
    <script>sourceMapSupport.install();</script>

    <!-- Test Environment -->
    <script src="../node_modules/mocha/mocha.js"></script>
    <script src="../node_modules/chai/chai.js"></script>

    <script>
        mocha.setup({ui: 'bdd', timeout: 5000});
    </script>

    <!-- Unit Tests -->
    <script src="../build/tests-bundle.js"></script>
    <script>
      mocha.run();
    </script>
  </body>
</html>
```

...and removing the mocha import in the test file (adding `/* eslint-env mocha */` at the top instead) and instead add this to Rollup:
```
    globals: {
        mocha: 'mocha',
        chai: 'chai'
    }
```

and change the intro to:

```
intro: 'if (typeof module !== "undefined") require("source-map-support").install();'
```

**Comment by w8r** [comment]
Oh sorry I totally missed your issue and PR
I will update everything and publish

**Comment by w8r** [comment]
I think I've added most of the things you requested. Thank you!
